config/routes.rb
Rails.application.routes.draw do
  get "/obras", to: "obras#index"

  get 'welcome/index'
    
    resources  :obras
    
    root 'welcome#index' 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/obra.rb
class Obra < ApplicationRecord
   validates :titulo, presence: true,
                     length:  { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController

  def index
    @obras = Obra.all
  end


  def show
    @obra = Obra.find(params[:id])   
  end

  def new
    @obra = Obra.new
  end

  def edit
    @obra = Obra.find(params[:id])
  end

  def create
    @obra = Obra.new(obra_params)
    
    if @obra.save
    redirect_to @obra
    else 
       render 'new'
  end
 end

  def update
    @obra = Obra.find(params[:id])
    
    if @obra.update(obra_params)
    redirect_to @obra
    else 
       render 'edit'
  end
  end

  def destroy
    @obra = Obra.find(params[:id])
    @obra.destroy

    redirect_to obras_path
  end

private
  def obra_params
    params.require(:obra).permit(:titulo, :autor)

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/obras/_form.html.erb
<%= form_with model: @obra, local: true do |form|  %>

<% if @obra.errors.any? %>
  <div id="error_explanation">
    <h2>
     <%= pluralize(@obra.errors.count, "error") %> por los que no se puede guardar 
     esta obra:
    </h2> 
   <u1>
   <% @obra.errors.full_messages.each do |msg|  %>
      <li><%= msg  %></li>
   <% end %>
   </u1>
   </div>
 <% end %>


<p>
  <%= form.label :titulo  %><br>
  <%= form.text_field :titulo  %>
</p>
<p>
  <%= form.label :autor  %><br>
  <%= form.text_field :autor %>
</p>

<p>
   <%= form.submit  %>
</p> 

<%  end %>

<%= link_to 'Volver', obras_path %>

app/views/obras/edit.html.erb
<h1>Edición</h1>

<%= render 'form' %>

<%= link_to 'Volver', obras_path %>

app/views/obras/index.html.erb
<h1> Listando Obras </h1>

<%= link_to 'Nueva obra', new_obra_path %>
<table>
<tr>
  <th>  Título  </th>
  <th>  Autor   </th>
  <th colspan="3"></th>
</tr>

<% @obras.each do |obra| %> 
  <tr>
    <td><%= obra.titulo %> </td>
    <td><%= obra.autor %> </td>
    <td><%= link_to 'Mostrar', obra_path(obra) %> </td>
    <td><%= link_to 'Edición', edit_obra_path(obra) %> </td>
    <td><%= link_to 'Borrar', obra_path(obra), 
                     method: :delete, 
                     data: {confirm: 'Está Ud.seguro?'} %> </td>
  </tr>
 <% end %>
</table>

app/views/obras/new.html.erb
<h1>Nuevo libro</h1>

<%= render 'form' %>


<%= link_to 'Volver', obras_path %>

app/views/obras/show.html.erb
<p>
  <strong>   Título:   </strong>
  <%= @obra.titulo  %>
</p>


<p>
  <strong>   Autor:   </strong>
  <%= @obra.autor  %>
</p>


<%= link_to 'Edición', edit_obra_path(@obra)  %>
<%= link_to 'Volver', obras_path  %>

app/views/welcome/index.html.erb
<h1> LIBROS </h1>
<%= link_to 'Libro', controller: 'obras' %>